---
- name: restart nova
  service: name={{ item }} state=restarted 
  with_items:
   - openstack-nova-api
   - openstack-nova-scheduler
   - openstack-nova-network
   - openstack-nova-cert
   - openstack-nova-console
   - openstack-nova-conductor

